# Generated by Django 3.2.3 on 2021-06-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profilepic', models.ImageField(default='default.jpg', upload_to='profilepic')),
                ('userid', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=200)),
                ('postct', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
            ],
        ),
    ]
