# Generated by Django 3.2.3 on 2021-06-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_post_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='curuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
            ],
        ),
    ]
