# Generated by Django 3.2.3 on 2021-06-03 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_curuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='curuser',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
