# Generated by Django 3.2.3 on 2021-06-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_curuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(default='profilepic/default.jpg', upload_to='profilepic'),
        ),
    ]
