# Generated by Django 3.2.3 on 2021-06-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_user_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
