# Generated by Django 3.2.3 on 2021-06-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_user_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
    ]
