# Generated by Django 3.2.3 on 2021-06-05 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='logintime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
