# Generated by Django 3.2.3 on 2021-06-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20210605_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='curuser',
        ),
        migrations.AddField(
            model_name='message',
            name='linkmessage',
            field=models.URLField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='message',
            name='textmessage',
            field=models.CharField(default='NULL', max_length=500),
        ),
    ]
