# Generated by Django 3.2.3 on 2021-06-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20210607_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='online',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
            ],
        ),
    ]
