# Generated by Django 3.2.9 on 2021-12-22 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionid', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
                ('problemid', models.CharField(max_length=200)),
                ('problemtitle', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('langid', models.IntegerField(default=0)),
                ('langname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('cerror', models.IntegerField(default=0)),
                ('rerror', models.IntegerField(default=0)),
                ('terror', models.IntegerField(default=0)),
                ('werror', models.IntegerField(default=0)),
                ('accept', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='correctsu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='totalsub',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
